apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      imagePullSecrets:
        - name: dockerregistrykey
      containers:
        - name: store-srv
          image: nikhil770/store-srv:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USERNAME
              value: 'root'
            - name: MYSQL_HOSTNAME
              value: mysql-cluster-ip-service
            - name: MYSQL_DATABASE
              value: 'mobilestore'
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpassword
                  key: MYSQLPASSWORD